# Generated by Django 6.1 on 2026-09-30 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$', 'Numéro invalide. Format international, chiffres uniquement, avec ou sans + (ex : +22670000000).')]),
        ),
    ]
