# Generated by Django 6.1 on 2026-10-05 17:08

from django.db import migrations, models
from django.db.models import F


def mark_existing_messages_as_notified(apps, schema_editor):
    """Les messages antérieurs à ce champ sont considérés comme déjà notifiés."""
    ContactMessage = apps.get_model("contact", "ContactMessage")
    ContactMessage.objects.filter(notified_at__isnull=True).update(notified_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_messages_as_notified, migrations.RunPython.noop),
    ]