# Generated by Django 6.1 on 2026-09-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_category_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('timeline', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('within_month', 'Dans le mois'), ('not_urgent', 'Pas pressé')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('converted', 'Converti'), ('closed', 'Clos')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_requests', to='service.service')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'db_table': 'devis',
            },
        ),
    ]
