# Generated by Django 6.1 on 2026-09-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='email',
            field=models.EmailField(blank=True, max_length=150),
        ),
    ]
