# Generated by Django 6.1 on 2026-09-30 10:35

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0003_alter_devis_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
