# Generated by Django 6.1 on 2026-10-05 11:46

from django.db import migrations, models
from django.db.models import F


def mark_existing_devis_as_notified(apps, schema_editor):
    """Les devis antérieurs à ce champ sont considérés comme déjà notifiés."""
    Devis = apps.get_model("devis", "Devis")
    Devis.objects.filter(notified_at__isnull=True).update(notified_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0004_alter_devis_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_devis_as_notified, migrations.RunPython.noop),
    ]