# Generated by Django 6.1 on 2026-10-06 08:21

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0005_devis_notified_at'),
        ('service', '0002_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Reçu le'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Notifié le'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_requests', to='service.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('converted', 'Converti'), ('closed', 'Clos')], default='new', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='timeline',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('within_month', 'Dans le mois'), ('not_urgent', 'Pas pressé')], max_length=20, verbose_name='Délai'),
        ),
    ]
