# Generated by Django 6.1 on 2026-10-06 08:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0006_alter_devis_created_at_alter_devis_email_and_more'),
        ('service', '0002_category_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='reçu le'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='email',
            field=models.EmailField(blank=True, max_length=150, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='nom complet'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='notifié le'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis_requests', to='service.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='status',
            field=models.CharField(choices=[('new', 'Nouveau'), ('contacted', 'Contacté'), ('converted', 'Converti'), ('closed', 'Clos')], default='new', max_length=20, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='devis',
            name='timeline',
            field=models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('within_month', 'Dans le mois'), ('not_urgent', 'Pas pressé')], max_length=20, verbose_name='délai'),
        ),
    ]
