# Generated by Django 6.1 on 2026-10-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0007_alter_devis_created_at_alter_devis_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='source',
            field=models.CharField(choices=[('site', 'Site web'), ('phone', 'Téléphone'), ('whatsapp', 'WhatsApp'), ('in_person', 'En personne')], default='site', max_length=20, verbose_name='source'),
        ),
    ]
