# Generated by Django 6.1 on 2026-10-09 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0008_devis_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='reçu le'),
        ),
    ]
