# Generated by Django 6.1 on 2026-09-28 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='service_area',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Format international, chiffres uniquement (ex : 22670000000).', max_length=30, validators=[django.core.validators.RegexValidator('^\\d{8,15}$', 'Chiffres uniquement, format international, sans + ni espaces (ex : 22670000000).')]),
        ),
    ]
