# Generated by Django 6.1 on 2026-09-30 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_business_hours_company_facebook_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$', 'Numéro invalide. Format international, chiffres uniquement, avec ou sans + (ex : +22670000000).')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$', 'Numéro invalide. Format international, chiffres uniquement, avec ou sans + (ex : +22670000000).')]),
        ),
    ]
