# Generated by Django 6.1 on 2026-10-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_phone_alter_company_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
