# Generated by Django 6.1 on 2026-10-06 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Entreprise', 'verbose_name_plural': 'Entreprises'},
        ),
    ]
